### ISSUE TITLE
Android API 26 : FATAL EXCEPTION:  java.lang.IllegalArgumentException: Required value was null.

### ISSUE THREAD

**Issue by MaqsoodAndroid** [wordpress-mobile/AztecEditor-Android#1081]
### Expected
App should not crash when render the html on API 26

### Observed

App is crashing

### Reproduced
<img width="930" alt="Screenshot 2024-05-15 at 2 27 59 PM" src="https://github.com/wordpress-mobile/AztecEditor-Android/assets/119599323/1b084596-d5ad-48e9-af0b-f90e094038fb">

#### Tested
[Android SDK build for arm 64] on [8.0.0] with [v2.1.3]

**Comment by MaqsoodAndroid** [comment]
- I want to use only to render the html. when i try to set

`visualEditor.isEnabled = false`
its crashed.

- The library version [v1.6.4] & above does not show any impact of implementing

`override fun getDefaultEditable(): Boolean {
        return false
    }`

- Question: is it actually possible to use Aztec as read only html renderer?

**Comment by nokite** [comment]
Any input on this? 
I have the same issue after upgrading Aztec to v2.1.4 (slightly different lines).
When I click on a link:

```
java.lang.IllegalArgumentException: Required value was null.
  at org.wordpress.aztec.AztecText.onCreateInputConnection(AztecText.kt:699)
  at android.view.inputmethod.InputMethodManager.createInputConnection(InputMethodManager.java:5008)
```
