### ISSUE TITLE
Crash report wpandroid alpha-42: Undo while uploading image crashes app

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#299]
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int org.xml.sax.Attributes.getLength()' on a null object reference
       at org.ccil.cowan.tagsoup.AttributesImpl.setAttributes(AttributesImpl.java:356)
       at org.ccil.cowan.tagsoup.AttributesImpl.<init>(AttributesImpl.java:83)
       at org.wordpress.android.editor.AztecEditorFragment$AttributesWithClass.<init>(AztecEditorFragment.java:636)
       at org.wordpress.android.editor.AztecEditorFragment.onMediaUploadProgress(AztecEditorFragment.java:590)
       at org.wordpress.android.ui.posts.EditPostActivity.onUploadProgress(EditPostActivity.java:990)
       at org.wordpress.android.ui.posts.EditPostActivity.onMediaUploaded(EditPostActivity.java:2299)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by 0nko** [comment]
The attribute retrieval updated & made safer to use (it does not return `null` anymore) by the [attributes PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/321) and the crash does not occur anymore.
