### ISSUE TITLE
Aztec consumes too much memory with a lot of images in it

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#420]
It seems there is a very high memory usage when a lot of pictures are added to the editor. 
From tests I run comparing the old visual editor with Aztec, it seems that the "old" works better in terms of memory consumption, and doesn't crash the app, instead Aztec seems to be more prone to OOM errors.

I investigated it a bit, and found out that `AztecDynamicImageSpan` do not use Weak references to the original drawable. Instead, its parent class `DynamicDrawableSpan` does use weak reference.
This could probably lead to some memory leak (Take it with a grain of salt) and resulting in high resource consumption. 
Ref: https://github.com/wordpress-mobile/WordPress-Android/issues/6283#issuecomment-315759297

**Comment by daniloercoli** [comment]
We should probably not pass a drawable in the constructor of `AztecDynamicImageSpan`, but a reference instead, and create the drawable when it's required (image is on the screen). See `DynamicDrawableSpan`.

**Comment by tonyr59h** [comment]
FYI, we're seeing OOM errors in Crashlytics that may be related:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 6885388 byte allocation with 4572224 free bytes and 4MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
       at android.graphics.drawable.VectorDrawable$VectorDrawableState.createCachedBitmapIfNeeded(VectorDrawable.java:834)
       at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:318)
       at org.wordpress.aztec.spans.AztecMediaSpan.draw(AztecMediaSpan.kt:76)
       at android.text.TextLine.handleReplacement(TextLine.java:858)
       at android.text.TextLine.handleRun(TextLine.java:941)
       at android.text.TextLine.drawRun(TextLine.java:398)
       at android.text.TextLine.draw(TextLine.java:196)
       at android.text.Layout.drawText(Layout.java:416)
       at android.widget.Editor.drawHardwareAccelerated(Editor.java:1747)
```

**Comment by 0nko** [comment]
I'm going to close this for now as @daniloercoli has made some improvements and the performance is acceptable. We can always come back and reopen it.
