### ISSUE TITLE
Crash report 7.8: OOB InlineFormatter.joinStyleSpans

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/AztecEditor-Android#455]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (-1 ... 24) starts before 0
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1021)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:592)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
       at org.wordpress.aztec.formatting.InlineFormatter.joinStyleSpans(InlineFormatter.kt:241)
       at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle(InlineFormatter.kt:168)
       at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle$default(InlineFormatter.kt:102)
       at org.wordpress.aztec.formatting.InlineFormatter.toggle(InlineFormatter.kt:20)
       at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:608)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:430)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:24)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:338)
       at android.view.View.performClick(View.java:4100)
```

**Comment by maxme** [comment]
I can't find that one in 8.8
