### ISSUE TITLE
Crash report 7.8: IllegalArgumentException, Kotlin not playing nice with Java?

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/AztecEditor-Android#456]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:5529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
       at org.wordpress.aztec.AztecAttributes.setValue(AztecAttributes.kt)
       at org.wordpress.android.editor.AztecEditorFragment.onMediaUploadSucceeded(AztecEditorFragment.java:735)
       at org.wordpress.android.ui.posts.EditPostActivity.onUploadSuccess(EditPostActivity.java:792)
       at org.wordpress.android.ui.posts.EditPostActivity.onMediaUploaded(EditPostActivity.java:2415)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
```

**Comment by mzorz** [comment]
I’ve been investigating this a bit - the only reason I could think of having an empty url there is that the actual `mediamodel` didn’t have one in the first place. i.e. one case I _think_  could be `MediaUtils.getPath()`  in  `MediaUtils.getRealPathFromURI` in `EditPostActivity.buildMediaModel()` might return null if the content descriptor is unknown ( as per `util/MediaUtils.getDocumentProviderPathKitkatOrHigher()`).
Particularly, it seems `MediaUtils.getRealPathFromURI` is what should be used in `PostUploadService.uploadImage()` instead of replicating the code there, and a probable cause for the mediamodel to have a null path when the file is uploaded.

Worth noting, this is all going to change now that the `async-media` work is merged into `develop`, so I guess it's probably better to wait for that, or maybe patch this particular NPE in the case many users are affected

**Comment by maxme** [comment]
@mzorz now that async is merged, can you check this is still an issue? (I guess the error was coming from a null `mediaUrl` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/f499b409950b1a879fd95bffccb369963907b234/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java#L738-L738))

**Comment by maxme** [comment]
Note: this happens in wpandroid 8.1 (with async) due to a null `remoteUrl` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/40f33424e5f86cad8678b9fc4933e8b517466ce8/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java#L860-L860)

**Comment by maxme** [comment]
In the hybrid editor this doesn't crash but we set a null URL in the HTML doc: https://github.com/wordpress-mobile/WordPress-Android/blob/3bcbed86225a133237adf1f7362a2e162a9f77a5/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L1135-L1136

**Comment by mzorz** [comment]
Closing via https://github.com/wordpress-mobile/WordPress-Android/pull/6626

**Comment by maxme** [comment]
Re-opening, apparently this still happens in recent versions of wpandroid (8.7 for example) but there are less frequent than before the patch.

**Comment by maxme** [comment]
Stack trace is actually a bit different, this happens only in `EditPostActivity.onMediaUploadCancelClicked`:

```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
       at org.wordpress.aztec.AztecAttributes.setValue(AztecAttributes.kt)
       at org.wordpress.android.editor.AztecEditorFragment.onMediaUploadSucceeded(AztecEditorFragment.java:902)
       at org.wordpress.android.ui.posts.EditPostActivity.onMediaRetryClicked(EditPostActivity.java:2476)
       at org.wordpress.android.editor.AztecEditorFragment.onMediaTapped(AztecEditorFragment.java:1325)
       at org.wordpress.android.editor.AztecEditorFragment.onImageTapped(AztecEditorFragment.java:1245)
       at org.wordpress.aztec.spans.AztecImageSpan.onClick(AztecImageSpan.kt:17)
       at org.wordpress.aztec.spans.AztecMediaClickableSpan.onClick(AztecMediaClickableSpan.kt:9)
       at org.wordpress.aztec.EnhancedMovementMethod.onTouchEvent(EnhancedMovementMethod.kt:77)
       at android.widget.TextView.onTouchEvent(TextView.java:10103)
       at android.view.View.dispatchTouchEvent(View.java:10779)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:738)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:607)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:569)
       at android.view.View.dispatchPointerEvent(View.java:11008)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
