### ISSUE TITLE
Crash (8.1 - 8.2): IndexOutOfBoundsException in AztecText.fromHtml

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#491]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (1 ... 1) ends beyond length 0
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
       at android.text.Selection.setSelection(Selection.java:76)
       at android.text.Selection.setSelection(Selection.java:87)
       at android.widget.EditText.setSelection(EditText.java:98)
       at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:743)
       at org.wordpress.aztec.AztecText.paste(AztecText.kt:1049)
       at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:960)
       at android.widget.Editor$ActionPopupWindow.onClick(Editor.java:3848)
       at android.view.View.performClick(View.java:5207)
       at android.widget.TouchPanelLayout.resetChildState(TouchPanelLayout.java:58)
       at android.widget.TouchPanelLayout.dispatchTouchEvent(TouchPanelLayout.java:46)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:1968)
       at android.view.View.dispatchPointerEvent(View.java:9526)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4267)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4133)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5959)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5933)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5894)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6062)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:5527)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/59a9954ebe077a4dccf69c54

**Comment by maxme** [comment]
Fixed by 8.3
