### ISSUE TITLE
Cut&Paste Crash - RuntimeException: PARAGRAPH span must start at paragraph boundary

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#501]
I had the editor with a long text in it. Different styles were applied to the text.
I selected a word and then pasted other chunk of text previously copied in the clipboard.

**Tested on Nexus 5X Android 7**

```
java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
 at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:687)
 at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
 at org.wordpress.aztec.util.SpanWrapper.setFlags(SpanWrapper.kt:20)
 at org.wordpress.aztec.AztecParser.markBlockElementsAsParagraphs(AztecParser.kt:255)
 at org.wordpress.aztec.AztecParser.fromHtml(AztecParser.kt:45)
 at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:737)
 at org.wordpress.aztec.AztecText.paste(AztecText.kt:1053)
 at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:964)
 at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3793)
 at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2301)
 at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:88)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
 at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:114)
 at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:394)
 at android.view.View.performClick(View.java:5637)
 at android.view.View$PerformClick.run(View.java:22429)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6121)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Related to https://github.com/wordpress-mobile/AztecEditor-Android/issues/481 ?

**Comment by maxme** [comment]
Another report, with some sample text:

```
Fatal Exception: java.lang.RuntimeException: ### START: 113, END: 114
---
### TEXT:Vindo-bem, versão: 21/10/2017
Jānuyū (ジャーヌユー) u1
Jaanuyuu - 21/10/2017
￼
Fyūsū (フュウースー) u1  
Fyuusuu - 21/10/2017
￼
       at org.wordpress.aztec.handlers.BlockHandler$Companion.set(BlockHandler.kt:116)
       at org.wordpress.aztec.formatting.BlockFormatter.removeBlockStyle(BlockFormatter.kt:212)
       at org.wordpress.aztec.AztecText.removeBlockStylesFromRange(AztecText.kt:950)
       at org.wordpress.aztec.formatting.LineBlockFormatter.applyHorizontalRule(LineBlockFormatter.kt:89)
       at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:651)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:430)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:24)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:338)
       at android.view.View.performClick(View.java:5716)
       at android.widget.TextView.performClick(TextView.java:10926)
       at android.widget.CompoundButton.performClick(CompoundButton.java:125)
       at android.view.View$PerformClick.run(View.java:22596)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:662)
       at org.wordpress.aztec.handlers.BlockHandler$Companion.set(BlockHandler.kt:114)
       at org.wordpress.aztec.formatting.BlockFormatter.removeBlockStyle(BlockFormatter.kt:212)
       at org.wordpress.aztec.AztecText.removeBlockStylesFromRange(AztecText.kt:950)
       at org.wordpress.aztec.formatting.LineBlockFormatter.applyHorizontalRule(LineBlockFormatter.kt:89)
       at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:651)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:430)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:24)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:338)
       at android.view.View.performClick(View.java:5716)
       at android.widget.TextView.performClick(TextView.java:10926)
       at android.widget.CompoundButton.performClick(CompoundButton.java:125)
       at android.view.View$PerformClick.run(View.java:22596)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by 0nko** [comment]
Hey @maxme, what version of wpandroid is this from? This data-logging has been removed a while ago so I think it's from an older version and this particular pasting crash has been addressed.

@daniloercoli I'm having trouble reproducing your stack trace. Do you have a specific text that I could use? Thanks!

**Comment by maxme** [comment]
Found in 8.4.1 - on Android 6 and 7.

**Comment by daniloercoli** [comment]
Nope @0nko, I was able to reproduce it constantly by 2 weeks ago, but just tested develop and could not reproduce it anymore. Tested on Nexus 5X - Android 7.0.

I can re-do a test later today.
