### ISSUE TITLE
Can't run demo app on pre 5.0.0 devices

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/AztecEditor-Android#508]
If you try to build and run current project on pre api 21 devices app will crash with this or similiar error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.wordpress.aztec, PID: 3107
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libhoudini.so" not found at java.lang.Runtime.loadLibrary(Runtime.java:364)
at java.lang.System.loadLibrary(System.java:526)
at com.android.tools.profiler.support.ProfilerService.<clinit>(ProfilerService.java:41)
at android.support.v4.app.SupportActivity.<init>(SupportActivity.java:68)
at android.support.v4.app.BaseFragmentActivityApi14.<init>(BaseFragmentActivityApi14.java:28)
at android.support.v4.app.BaseFragmentActivityApi16.<init>(BaseFragmentActivityApi16.java:34)
at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:65)
at android.support.v7.app.AppCompatActivity.<init>(AppCompatActivity.java:61)
at org.wordpress.aztec.demo.MainActivity.<init>(MainActivity.kt:51)
at java.lang.Class.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:1208)
at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

Checking out dev branch at different points suggests that the issue was introduced with this pr #467

**Comment by 0nko** [comment]
@khaykov, with the current `develop` I am able to run the demo app without a crash on API 16, 18 and 21. Can you verify please?

**Comment by 0nko** [comment]
It seems @daniloercoli can't reproduce this either.
