### ISSUE TITLE
Large text blocks make the app crash

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#561]
### Expected
AztecText should handle a big piece of text

### Observed
Pasting a 1mb block of text twice at the end of the demo app, (sample content [used here](http://www.sample-videos.com/text/Sample-text-file-1000kb.txt)) then 
scrolling up and down, adding some text on the keyboard you’ll see that it lags a lot, but it works and keeps formatted text as you enter it, scroll up/down and it will be kept. It even works well when rotating the device as well.

At some point, if you go all the way down and tap on the last position (right of the last character) it will crash with this stacktrace:

```
12-05 16:25:08.962 6516-6516/org.wordpress.aztec D/AndroidRuntime: Shutting down VM
12-05 16:25:08.964 6516-6516/org.wordpress.aztec E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.wordpress.aztec, PID: 6516
                                                                   java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1160676 bytes
                                                                       at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:884)
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:467)
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:443)
                                                                       at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6942)
                                                                       at android.view.View.performClick(View.java:6264)
                                                                       at android.view.View$PerformClick.run(View.java:24697)
                                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: android.os.TransactionTooLargeException: data parcel size 1160676 bytes
                                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                                       at android.os.BinderProxy.transact(Binder.java:748)
                                                                       at android.view.autofill.IAutoFillManager$Stub$Proxy.updateSession(IAutoFillManager.java:452)
                                                                       at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:879)
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:467) 
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:443) 
                                                                       at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6942) 
                                                                       at android.view.View.performClick(View.java:6264) 
                                                                       at android.view.View$PerformClick.run(View.java:24697) 
                                                                       at android.os.Handler.handleCallback(Handler.java:789) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
12-05 16:25:08.968 914-1311/? W/ActivityManager:   Force finishing activity org.wordpress.aztec/.demo.MainActivity
```

### Reproduced
1. start the demo app
2. paste a big block of text, 2mb
3. scroll up and down, rotate, insert some text in the middle and give it some format
4. at some point, scroll all the way down and try to position the cursor at the very end of the content
5. see the crash happen

#### Tested
[Google Pixel] on [Android 8.0]

**Comment by mzorz** [comment]
Setting the `low priority` label as this kind of thing is going to be tackled by Gutenberg block strategy
