### ISSUE TITLE
Crash report WPAndroid 9.0: PARAGRAPH span must start at paragraph boundary

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#578]
Observed in WPAndroid 9.0, Android 7:
(more information in crash report)
```
Fatal Exception: java.lang.RuntimeException: ### START: 49, END: 50
￼
​
       at org.wordpress.aztec.handlers.BlockHandler$Companion.set(BlockHandler.kt:115)
       at org.wordpress.aztec.formatting.BlockFormatter.removeBlockStyle(BlockFormatter.kt:225)
       at org.wordpress.aztec.AztecText.removeBlockStylesFromRange(AztecText.kt:1034)
       at org.wordpress.aztec.formatting.LineBlockFormatter.applyHorizontalRule(LineBlockFormatter.kt:101)
       at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:720)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:435)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:29)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:343)
       at android.view.View.performClick(View.java:5647)
       at android.widget.CompoundButton.performClick(CompoundButton.java:122)
       at android.view.View$PerformClick.run(View.java:22462)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
Caused by java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:687)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
       at org.wordpress.aztec.handlers.BlockHandler$Companion.set(BlockHandler.kt:113)
       at org.wordpress.aztec.formatting.BlockFormatter.removeBlockStyle(BlockFormatter.kt:225)
       at org.wordpress.aztec.AztecText.removeBlockStylesFromRange(AztecText.kt:1034)
       at org.wordpress.aztec.formatting.LineBlockFormatter.applyHorizontalRule(LineBlockFormatter.kt:101)
       at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:720)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:435)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:29)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:343)
       at android.view.View.performClick(View.java:5647)
       at android.widget.CompoundButton.performClick(CompoundButton.java:122)
       at android.view.View$PerformClick.run(View.java:22462)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

link to crash report nbr `issues/5a395c288cb3c2fa633cfc26`

**Comment by daniloercoli** [comment]
Related to the fix made here: https://github.com/wordpress-mobile/AztecEditor-Android/pull/539/files
