### ISSUE TITLE
Crash report: IndexOutOfBoundsException in AztecText.toHtml

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#582]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (11954 ... 11953) has end before start
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1258)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:102)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:50)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:904)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:890)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:706)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1005)
       at org.wordpress.android.ui.posts.EditPostActivity.access$1000(EditPostActivity.java:155)
       at org.wordpress.android.ui.posts.EditPostActivity$5.run(EditPostActivity.java:1024)
       at java.lang.Thread.run(Thread.java:762)
``` 
http://crashes.to/s/b71d5f2979a

**Comment by daniloercoli** [comment]
Argh, I had added logging here https://github.com/wordpress-mobile/AztecEditor-Android/pull/571 but probably we should log the text that caused the issue to the exception, otherwise the text is not being logged in Fabric.io.

**Comment by daniloercoli** [comment]
Dup of #452

**Comment by hypest** [comment]
I can still see instances of this error in v9.4 Crashlytics report and it doesn't exactly look like the same stacktrace as #452 so, reopening.

Crashlytics ref: 5a804acf8cb3c2fa63cdfba8
