### ISSUE TITLE
Crash report wpandroid 9.2 (Aztec v1.1): OOB in AztecText.toPlainHtml

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#625]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=898; index=898
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:912)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:826)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:76)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:49)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1047)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1031)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:739)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1054)
       at org.wordpress.android.ui.posts.EditPostActivity.access$1100(EditPostActivity.java:158)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:519)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniloercoli** [comment]
This is a dupe of #452 - For which we've just added more logging [here](https://github.com/wordpress-mobile/AztecEditor-Android/pull/623).
