### ISSUE TITLE
Crash report -  OOB in org.wordpress.aztec.EnhancedMovementMethod.onTouchEvent

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#626]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
       at android.text.Selection.setSelection(Selection.java:76)
       at android.text.method.ArrowKeyMovementMethod.onTouchEvent(ArrowKeyMovementMethod.java:310)
       at org.wordpress.aztec.EnhancedMovementMethod.onTouchEvent(EnhancedMovementMethod.kt:83)
       at android.widget.TextView.onTouchEvent(TextView.java:10101)
       at android.view.View.dispatchTouchEvent(View.java:10775)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:738)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:568)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1896)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3247)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:530)
       at android.view.View.dispatchPointerEvent(View.java:11004)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5111)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4963)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4494)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4547)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4513)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4646)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4521)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4703)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4494)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4547)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4513)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4521)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4494)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7003)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6934)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6895)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7113)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/598312aebe077a4dcc8b238f?time=last-seven-days

**Comment by daniloercoli** [comment]
Closing this since it's an issue limited to few users on Samsung 7.0 due to a problem on those devices. We're catching details in case of crashes now, so we can try to reproduce the issue better if the number of crashes increase.
