### ISSUE TITLE
Crash in 1.1: IOOB in HeadingHandler.handleNewlineInBody

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#629]
Happen in v1.1 (wpandroid 9.2)

```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (159 ... 90) has end before start
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1302)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
       at org.wordpress.aztec.handlers.BlockHandler$Companion.set(BlockHandler.kt:121)
       at org.wordpress.aztec.handlers.HeadingHandler$Companion.cloneHeading(HeadingHandler.kt:58)
       at org.wordpress.aztec.handlers.HeadingHandler.handleNewlineInBody(HeadingHandler.kt:39)
       at org.wordpress.aztec.handlers.BlockHandler.handleTextChanged(BlockHandler.kt:59)
       at org.wordpress.aztec.watchers.BlockElementWatcher.onTextChanged(BlockElementWatcher.kt:72)
       at android.widget.TextView.sendOnTextChanged(TextView.java:9359)
       at android.widget.TextView.setText(TextView.java:5395)
       at android.widget.TextView.setText(TextView.java:5248)
       at android.widget.EditText.setText(EditText.java:113)
       at android.widget.TextView.setText(TextView.java:5205)
       at org.wordpress.aztec.AztecText.executeEvent(AztecText.kt:1557)
       at org.wordpress.aztec.watchers.event.sequence.ObservationQueue.processQueue(ObservationQueue.kt:69)
       at org.wordpress.aztec.watchers.event.sequence.ObservationQueue.add(ObservationQueue.kt:35)
       at org.wordpress.aztec.AztecText.afterTextChanged(AztecText.kt:901)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9375)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11917)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1262)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:574)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6637)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by daniloercoli** [comment]
This was fixed in #632
