### ISSUE TITLE
Crash 9.3/9.4: RuntimeException: PARAGRAPH span must end at paragraph boundary

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#639]
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must end at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:683)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:97)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:49)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1053)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1037)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:794)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1091)
       at org.wordpress.android.ui.posts.EditPostActivity.access$1100(EditPostActivity.java:161)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:524)
       at java.lang.Thread.run(Thread.java:818)
```

internal ref: `5a804acf8cb3c2fa63cdfba8`

**Comment by maxme** [comment]
http://crashes.to/s/4a52754d0c9
