### ISSUE TITLE
Crash: IOOB at TextView.pasteClipBoardData()

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/AztecEditor-Android#640]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: 12, -11
       at android.text.PackedIntVector.deleteAt(PackedIntVector.java:218)
       at android.text.DynamicLayout.reflow(DynamicLayout.java:311)
       at android.text.DynamicLayout.-wrap0(DynamicLayout.java)
       at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:662)
       at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:691)
       at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1248)
       at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:652)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:582)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
       at android.widget.TextView.pasteClipBoardData(TextView.java:625)
       at android.widget.TextView.-wrap10(TextView.java)
       at android.widget.TextView$TextViewClipboardEventListener$1.run(TextView.java:533)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by hypest** [comment]
This crash seems similar to #611 but because the stacktrace is a bit different I opened a separate ticket.

**Comment by marecar3** [comment]
Closing this one in favor of: https://github.com/wordpress-mobile/WordPress-Android/issues/8827
