### ISSUE TITLE
Crash report wpandroid 9.6: PARAGRAPH span must start at paragraph boundary

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#649]
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:102)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:50)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1123)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1107)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:796)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1131)
       at org.wordpress.android.ui.posts.EditPostActivity.access$800(EditPostActivity.java:162)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:531)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by maxme** [comment]
http://crashes.to/s/1fbb72bc5ac

**Comment by maxme** [comment]
It looks like this one was introduced with wpandroid 9.6 (Aztec v1.3)

**Comment by daniloercoli** [comment]
Related to https://github.com/wordpress-mobile/AztecEditor-Android/issues/639

**Comment by designsimply** [comment]
**30-day impact:** ~1 per day
**Users affected:** 23 in the last 30d
**Last seen in:** 12.5

<sup>https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/</sup>
