### ISSUE TITLE
Crash report wpandroid 9.6: IOOB in AztecText.onTextContextMenuItem

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/AztecEditor-Android#651]
WPAndroid 9.6 / Aztec 1.3

```
Fatal Exception: java.lang.IndexOutOfBoundsException: 32, -31
       at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
       at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
       at android.text.DynamicLayout.-wrap0(Unknown Source)
       at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:752)
       at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:781)
       at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1292)
       at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:647)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at android.widget.TextView.paste(TextView.java:11193)
       at android.widget.TextView.onTextContextMenuItem(TextView.java:10841)
       at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:1304)
       at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3976)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2459)
       at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:96)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
       at com.android.internal.view.FloatingActionMode.lambda$-com_android_internal_view_FloatingActionMode_4856(FloatingActionMode.java:121)
       at com.android.internal.view.-$Lambda$IoKM3AcgDw3Ok5aFi0zlym2p3IA.$m$0(Unknown Source:4)
       at com.android.internal.view.-$Lambda$IoKM3AcgDw3Ok5aFi0zlym2p3IA.onMenuItemClick(Unknown Source)
       at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:425)
       at android.view.View.performClick(View.java:6294)
       at android.view.View$PerformClick.run(View.java:24770)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by daniloercoli** [comment]
Checked out tag `1.3.1` and verified that the error is happening on this line of code here:
https://github.com/wordpress-mobile/AztecEditor-Android/blob/c17ab3f84b7f6b9a23e782aea41c91bcf4f27f08/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L1304
That's a call to the Android TextEdit's method.

Will try to put together a fix in `develop`.
