### ISSUE TITLE
OOB Crash in AztecAttributes  setValue/removeAttribute

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#705]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=5; index=7
       at org.xml.sax.helpers.AttributesImpl.addAttribute(AttributesImpl.java:385)
       at org.wordpress.aztec.AztecAttributes.setValue(AztecAttributes.kt:10)
       at org.wordpress.aztec.source.CssStyleFormatter$Companion.addStyleAttribute(CssStyleFormatter.kt:123)
       at org.wordpress.aztec.AztecParser.withinNestable(AztecParser.kt:386)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:359)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:311)
       at org.wordpress.aztec.AztecParser.toHtml(AztecParser.kt:92)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1142)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1105)
       at org.wordpress.aztec.AztecText.toHtml$default(AztecText.kt:1104)
       at org.wordpress.aztec.AztecText.toFormattedHtml(AztecText.kt:1146)
       at org.wordpress.aztec.History.beforeTextChanged(History.kt:42)
       at org.wordpress.aztec.AztecText$addHistoryLoggingWatcher$historyLoggingWatcher$1.beforeTextChanged(AztecText.kt:480)
       at android.widget.TextView.sendBeforeTextChanged(TextView.java:9144)
       at android.widget.TextView.access$1600(TextView.java:326)
       at android.widget.TextView$ChangeWatcher.beforeTextChanged(TextView.java:11954)
       at android.text.SpannableStringBuilder.sendBeforeTextChanged(SpannableStringBuilder.java:1027)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:523)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:494)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:691)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:447)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Internal Ref: 5a8423408cb3c2fa6302badc

**Comment by daniloercoli** [comment]
Similar problem in `removeAttribute`.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: Attempt to modify attribute at illegal index: -1
       at org.xml.sax.helpers.AttributesImpl.badIndex(AttributesImpl.java:603)
       at org.xml.sax.helpers.AttributesImpl.removeAttribute(AttributesImpl.java:451)
       at org.wordpress.aztec.AztecAttributes.removeAttribute(AztecAttributes.kt:23)
       at org.wordpress.aztec.source.CssStyleFormatter$Companion.removeStyleAttribute(CssStyleFormatter.kt:95)
       at org.wordpress.aztec.AztecParser.withinNestable(AztecParser.kt:380)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:359)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:311)
       at org.wordpress.aztec.AztecParser.toHtml(AztecParser.kt:92)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1142)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1105)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:864)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1262)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:179)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:559)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniloercoli** [comment]
Adding here another problem with the internal state of AztecAttributes - This time is the `toString` method that causes the OOB:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=5; index=6
       at org.xml.sax.helpers.AttributesImpl.getLocalName(AttributesImpl.java:126)
       at org.wordpress.aztec.AztecAttributes.toString(AztecAttributes.kt:34)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at org.wordpress.aztec.spans.IAztecSpan$DefaultImpls.getStartTag(IAztecSpan.kt:15)
       at org.wordpress.aztec.spans.IAztecParagraphStyle$DefaultImpls.getStartTag(IAztecParagraphStyle.kt)
       at org.wordpress.aztec.spans.HiddenHtmlSpan.getStartTag(HiddenHtmlSpan.kt:6)
       at org.wordpress.aztec.AztecParser.withinNestable(AztecParser.kt:397)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:359)
       at org.wordpress.aztec.AztecParser.withinNestable(AztecParser.kt:400)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:359)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:311)
       at org.wordpress.aztec.AztecParser.toHtml(AztecParser.kt:92)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1142)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1105)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:864)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1262)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:179)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:559)
       at java.lang.Thread.run(Thread.java:818)```

**Comment by khaykov** [comment]
Still happening :(
