### ISSUE TITLE
RuntimeException - AztecMediaSpan.draw

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/AztecEditor-Android#748]
```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c4afd26
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:600)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:537)
       at org.wordpress.aztec.spans.AztecMediaSpan.draw(AztecMediaSpan.kt:66)
       at android.text.TextLine.handleReplacement(TextLine.java:853)
       at android.text.TextLine.handleRun(TextLine.java:936)
       at android.text.TextLine.drawRun(TextLine.java:395)
       at android.text.TextLine.draw(TextLine.java:193)
       at android.text.Layout.drawText(Layout.java:355)
       at android.widget.Editor.drawHardwareAccelerated(Editor.java:1390)
       at android.widget.Editor.onDraw(Editor.java:1315)
       at android.widget.TextView.onDraw(TextView.java:5423)
       at android.view.View.draw(View.java:15139)
       at android.view.View.updateDisplayListIfDirty(View.java:14073)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.draw(View.java:15142)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at android.widget.ScrollView.draw(ScrollView.java:1697)
       at android.view.View.updateDisplayListIfDirty(View.java:14073)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.draw(View.java:15142)
       at android.view.View.updateDisplayListIfDirty(View.java:14073)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.draw(View.java:15142)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
       at android.view.View.updateDisplayListIfDirty(View.java:14073)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.updateDisplayListIfDirty(View.java:14068)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.View.draw(View.java:14863)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3443)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3231)
       at android.view.View.draw(View.java:15142)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2612)
       at android.view.View.updateDisplayListIfDirty(View.java:14073)
       at android.view.View.getDisplayList(View.java:14096)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5311)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

Internal Ref: 5a2735cd61b02d480df3abcc

**Comment by daniloercoli** [comment]
I was able to reproduce the problem.
- Start the app and go to posts list
- Tap on Edit for a post that contains lot of pictures
- Once the editor is on the screen and the placeholders visible tap the home screen
- Wait a couple of secs until some pictures are loaded from the network
- Re-open the app

```
   --------- beginning of crash
10-03 09:40:30.813 11435-11435/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 11435
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2caa418
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at org.wordpress.aztec.spans.AztecMediaSpan.draw(AztecMediaSpan.kt:66)
        at android.text.TextLine.handleReplacement(TextLine.java:910)
        at android.text.TextLine.handleRun(TextLine.java:1054)
        at android.text.TextLine.drawRun(TextLine.java:398)
        at android.text.TextLine.draw(TextLine.java:226)
        at android.text.Layout.drawText(Layout.java:539)
        at android.widget.Editor.drawHardwareAcceleratedInner(Editor.java:1813)
        at android.widget.Editor.drawHardwareAccelerated(Editor.java:1732)
        at android.widget.Editor.onDraw(Editor.java:1672)
        at android.widget.TextView.onDraw(TextView.java:6882)
        at android.view.View.draw(View.java:19192)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at android.widget.ScrollView.draw(ScrollView.java:1739)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
10-03 09:40:30.815 11435-11435/org.wordpress.android E/AndroidRuntime:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-03 09:40:30.815 11435-11435/org.wordpress.android E/WordPress-EDITOR: HTML content of Aztec Editor before the crash:
```

**Comment by daniloercoli** [comment]
Fix wp-android side [here](https://github.com/wordpress-mobile/WordPress-Android/pull/8397).
