### ISSUE TITLE
java.lang.IndexOutOfBoundsException: setSpan()

### ISSUE THREAD

**Issue by yangshibai** [wordpress-mobile/AztecEditor-Android#848]
When set  aztec.visualEditor.filters = arrayOf<InputFilter>(InputFilter.LengthFilter(1000)) ,it menas EditText MaxLength is 1000，next I paste piece of text with more than 500 words, the
first time is all right ,but the second time I continue paste this text ,the application crashed。

     This is the crash Log:

 java.lang.IndexOutOfBoundsException: setSpan (1272 ... 1272) ends beyond length 1000
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1309)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at android.widget.EditText.setSelection(EditText.java:127)
        at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:1158)
        at org.wordpress.aztec.AztecText.paste(AztecText.kt:1598)
        at org.wordpress.aztec.AztecText.paste$default(AztecText.kt:1557)
        at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:1493)
        at android.widget.Editor$ActionPopupWindow.onClick(Editor.java:4327)
        at android.view.View.performClick(View.java:6266)
        at android.widget.TouchPanelLayout.resetChildState(TouchPanelLayout.java:58)
        at android.widget.TouchPanelLayout.dispatchTouchEvent(TouchPanelLayout.java:46)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2397)
        at android.view.View.dispatchPointerEvent(View.java:11975)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4836)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4647)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4183)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4236)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4202)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4329)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4210)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4386)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4183)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4236)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4202)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4210)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4183)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6743)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6717)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6678)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6849)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:249)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

    Finally  I  found this method in AztecText class : consumeCursorPosition() calculate is wrong

**Comment by Riya1295** [comment]
Any update or any solution for this issue?

**Comment by Bibazavr** [comment]
Hello!

I'm facing same error and sure that problem happened [there](https://github.com/wordpress-mobile/AztecEditor-Android/blob/806c3a426294ed5ceb640286a90805cd06da8b03/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L1547)

Because lib setting cursor while ignoring all filters
