### ISSUE TITLE
Crash IllegalArgumentException: Center point is not inside any of the rectangles

### ISSUE THREAD

**Issue by sergpetrov** [wordpress-mobile/AztecEditor-Android#880]
My app is using Aztec editor and I see many crash reports with such exception.
I was able to reproduce for one case but I believe that it has more cases with the same problem. 

### Reproduced
1. Add some empty block style (quote for example).
2. Long tap.
3. Choose "Select all" from the context menu.

Video with the crash in Aztec demo app: https://drive.google.com/file/d/1BkqoL9gp0e5oEwdO2e_P5SOMqTrmDZ0f/view?usp=sharing

Crash log:
```
    Process: org.wordpress.aztec, PID: 29043
    java.lang.IllegalArgumentException: Center point is not inside any of the rectangles!
        at android.widget.SmartSelectSprite.startAnimation(SmartSelectSprite.java:392)
        at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:325)
        at android.widget.SelectionActionModeHelper.lambda$l1f1_V5lw6noQxI_3u11qF753Iw(Unknown Source:0)
        at android.widget.-$$Lambda$SelectionActionModeHelper$l1f1_V5lw6noQxI_3u11qF753Iw.accept(Unknown Source:4)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:998)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:952)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-12-04 10:46:34.373 29043-29043/org.wordpress.aztec E/WordPress-EDITOR: HTML content of Aztec Editor before the crash:
2019-12-04 10:46:34.377 29043-29043/org.wordpress.aztec E/WordPress-EDITOR: <blockquote></blockquote>
```

**Comment by NStreet8579** [comment]
Facing Same issue. Please help!

**Comment by NStreet8579** [comment]
Hi @sergpetrov , Can provide that video sample agian, link is broken, i'm also getting the exact crash, but not able to recreate the crash

**Comment by AkshayOptimumbrew** [comment]
Faced same issue is that any way to reproduce this issue?

**Comment by khaykov** [comment]
This issue is still present, and I was able to reproduce with the instructions from this issue. Original fix addressed the case where you pressed "Select All". The problem is that some device manufacturers add their own options for context menu. I found that one of my test One Plus devices has an "Select" option that also triggers the crash. I'm adding a better fix for this.
